name:      Andrea Pavoni
url:       http://andreapavoni.com

# Comments
disqus:
  shortname: apeacox

# Analytics
analytics:
  google:
    id: 'UA-9419221-5'

# Jekyll stuff
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     ['Rakefile', 'Gemfile', 'Gemfile.lock']
timezone:    nil

future:      false
show_drafts: nil
limit_posts: 0
pygments:    true

relative_permalinks: false
permalink:     '/blog/:year/:month/:title'

paginate_path: '/blog/page/:num'
paginate: 5

markdown:      maruku
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false

#
# Sitemap generator
#
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/feed/index.xml"
    - "/404.html"
  include_posts:
    - "/index.html"
    - "blog"
  # change_frequency_name: "change_frequency"
  # priority_name: "priority"
